# Welcome {.unnumbered}

Bienvenidos al curso de Microeconomía II, en este sitio web trataremos de recordar y fundamentar la temática sobre las *matemáticas de la optimización*, tema fundamental para la comprensión de la asignatura. Aquí preparo un resumen del libro de Nicholson capítulo 2, si desea profundizar más al respecto, sugiero revise el capítulo completo ingresando al siguiente [link.](https://elvisjgblog.files.wordpress.com/2019/04/teorc3ada-microeconc3b3mica-9c2b0-edicic3b3n-walter-nicholson.pdf)

Muchos de los modelos económicos parten del supuesto que un agente quiere determinar el valor óptimo de una función. En el caso de los consumidores, esa función mide la utilidad que estos obtienen de sus compras y, en el de las empresas, mide las ganancias de éstas. Sin embargo, en ambos casos, las cuestiones matemáticas formales de la solución son muy similares. En este material se analizarán las matemáticas que son comunes a todo este tipo de problemas. Para aquellos que esten familiarizados con el cálculo multivariante, este material servira de repaso. Para aquellos que sólo estén familiarizados con algunos conceptos del cálculo básico, este material les proporcionará las bases necesarias para comenzar a analizar el cálculo aplicado a la construcción de modelos microeconómicos.
