# Maximización con Restricciones

Hasta ahora nos hemos centrado en determinar el valor máximo de una función sin restringir la posibilidad de elegir entre las $x$ disponibles. Sin embargo, en la mayor parte de los problemas económicos, no todos los valores de las $x$ son factibles. Por ejemplo, en muchas situaciones es necesario que todas las $x$ sean positivas. Este requisito se presentaría en el caso del problema que afronta el administrador que elige el nivel de producción que maximiza las ganancias, o sea que una producción negativa no tendría sentido. Dado que no podemos elegir libremente entre todas las $x$, y tal vez no sea tan grande como podría ser. Así, diríamos que las restricciones son inactivas si se puede obtener el mismo nivel de $y$ indepedientemente de que se imponga o no la restricción.

## Método del Multiplicador Lagrangiano

Un método para resolver los problemas de maximización con restricciones es el *método del multiplicador lagrangiano,* el cual entraña un inteligente truco matemático que también tiene una interpretación económica muy útil. La lógica de este método es bastante sencilla, pero aquí no se pretende hacer una presentación rigurosa. La técnica lagrangiana introduce una variable adicional (el multiplicador lagrangiano), el cual no sólo ayuda a resolver el problema en cuestión (puesto que ahora hay $n+1$ ecuaciones en $n+1$ incógnitas), sino que también tiene una interpretación útil en diversas circustancias económicas.

## El Problema Formal

Mas concretamente, suponga que desea calcular los valores de $x_1,x_2, . . . , x_n$ que maximizan

$$
y = f(x_1,x_2, . . . , x_n)
$$

sujeto a una restrición que sólo permite utilizar ciertos valores de las $x$. Una forma general de escribir esa restricción es

$$
g(x_1,x_2, . . . , x_n) = 0
$$

donde la función $g$ representa la relación que se debe cumplir en todas las $x$.

## Condiciones de Primer Orden

El método del multiplicador lagrangiano parte de la formulación de la expresión

$$
L = f(x_1,x_2, . . . , x_n) + \lambda g(x_1,x_2, . . . , x_n)\hspace{1cm} (4)$$

donde $\lambda$ es una variable adiconal llamada multiplicador lagrangiano. consideraremos a $\lambda$ también una variable (además de las $x$). A partir de la ecuación (4) las condiciones para alcanzar un punto critico son

$$
\begin{eqnarray}
\frac{\partial L}{\partial x_1} &=& f_1 + \lambda g_1 = 0\\[0.2cm]
\frac{\partial L}{\partial x_2} &=& f_2 + \lambda g_2 = 0\\[0.2cm]
&\vdots&\\[0.2cm]
\frac{\partial L}{\partial x_n} &=& f_n + \lambda g_n = 0\\[0.2cm]
\frac{\partial L}{\partial \lambda} &=& g(x_1, x_2, . . . , x_n) = 0
\end{eqnarray}
$$

Así, las ecuaciones previas son las condiciones para obtener un punto crítico de la función $L$. Notese que hay $n+1$ ecuaciones (una para cada $x$ y otra más para $\lambda$) en $n+1$ incógnitas. En general, es posible resolver las ecuaciones para $x_1,x_2, . . . , x_n$, y para $\lambda$.

### Interpretación del Multiplicador Lagrangiano

Hasta aquí se ha utilizado el multiplicador lagrangiano $(\lambda)$ únicamente como un "truco" matemático para llegar a la solución que se quería. De hecho, esta variable también tiene una importante interpretación económica, la cual será fundamental para nuestro análisis. Para desarrollar esta interpretación, es necesario volver a escribir las primeras $n$ ecuaciones como

$$
\frac{f_1}{-g_1} = \frac{f_2}{-g_2} = . . . = \frac{f_n}{-g_n} = \lambda \hspace{2cm} (5)
$$

En otras palabras, en el punto, máximo, la proporción de $f_i$ respecto a $g_i$ es la misma para todas las $x_i$. Los numeradores de las ecuaciones previas son las contribuciones marginales de cada $x_i$ obtendrá en la función que se está maximizando (es decir $f$).

Utilizando terminología actual, podría escribirse esta restricción de forma implícita como

$$
g(x_1, x_2) = F - p_1x_1 - p_2x_2 = 0
$$

En esta situación, se tendría

$$
-g_i = p_i
$$

y la derivada $-g_i$ refleja, en efecto, el costo marginal por unidad derivado de utilizar $x_i$. Prácticamente todos los problemas de optimización que se encontrarán en capítulos posteriores hacen una interpretación similar de los denominadores de la ecuaciones (5).

### El multiplicador lagrangiano como proporción de costos a beneficios

Ahora es posible interpretar las ecuaciones (5) en forma intuitiva. Estas indican que, para los valores óptimos de las $x$, la proporción de beneficios marginales por incrementar $x_i$ con relación a los costos marginales por incrementar $x_i$ debería ser la misma para cada $x$.

También es posible interpretar el multiplicador lagrangiano $(\lambda)$ a la luz de este análisis. $\lambda$ es la proporción común de costos a beneficios de todas las $x$. Es decir,

$$
\lambda = \frac{beneficio\hspace{0.1cm} marginal\hspace{0.1cm}de\hspace{0.1cm} x_i}{costo\hspace{0.1cm}marginal\hspace{0.1cm} de \hspace{0.1cm}x_i}
$$

para cada $x_i$. Si relajáramos lijeramente la restricción, no importaría cuál de las $x$ cambia (de hecho, podrían variarse todas las $x$ porque, en el margen, cada una promete la misma proporción de beneficios respecto a los costos). En consecuencia, el multiplicador lagrangiano proporciona una medida de cómo esta relajación general de la restricción afectaria el valor de $y$. En consecuencia, $\lambda$ asigna un *precio sombra* a la restricción.

-   Un $\lambda$ alto indica que se podría aumentar $y$ sustancialmente si se relaja la restricción, porque cada $x$ tiene una proporción alta de costos a beneficios.

-   De otra forma, un valor bajo de $\lambda$, indica que no es posible ganar mucho si se relaja la restricción.

-   Si la restricción es inactiva en absoluto, entonces $\lambda$ tendrá un valor de cero, indicando así que la restricción no limita el valor de $y$.

También es posible demostrar esta interpretación de $\lambda$ utilizando el teorema del *Envolvente* como se describira posterioremente.

## Ejemplo

Supongamos que el objetivo de un individuo es maximizar un problema del área de la salud.

$$
y = -x_1^2 + 2x_1 - x_2^2 + 4x_2 + 5
$$

y suponga que las opciones de $x_1$ y $x_2$ están restringidas por el hecho de que el individuo sólo tolera una dosis de medicamentos por día. Es decir,

$$
x_1 + x_2 = 1
$$

Para lograr el objetivo, planteemos la expresión Lagrangiana:

$$
L = -x_1^2 + 2x_1 - x_2^2 + 4x_2 + 5 + \lambda(1 - x_1 - x_2)
$$

Si derivamos $L$ respecto a $x_1, x_2$ y $\lambda$ se obtiene la siguiente condición necesaria para obtener un máximo con restricciones:

$$
\begin{eqnarray}
\frac{\partial L}{\partial x_1} &=& -2x_1 + 2 - \lambda = 0\\[0.2cm]
\frac{\partial L}{\partial x_2} &=& -2x_2 + 4 - \lambda = 0\\[0.2cm]
\frac{\partial L}{\partial \lambda} &=& 1 - x_1 - x_2 = 0
\end{eqnarray}
$$

Se debe resolver estas ecuaciones para obtener los valores óptimos de $x_1,x_2$ y $x_2$. Al utilizar la primera y la segunda ecuación se obtiene

$$
-2x_1 + 2 = \lambda = -2x_2 + 4$$

o

$$
x_1 = x_2 -1 
$$

La sustitución de este valor por $x_1$ en la restricción ofrece la solución:

$$
x_2 = 1\\
x_1 = 0
$$

En otras palabras, si esta persona sólo tolera una dosis de medicamentos, entonces debe optar por tomar sólo el segundo medicamento. Al utilizar una de las dos primeras ecuaciones, es fácil completar la solución al demostrar que

$$
\lambda = 2
$$

Por tanto, esta es la solución al problema de maximización con restricciones. Si $x_1 = 0, x_2 = 1$, entonces $y$ toma el valor de 8.

*¿Suponga que este individuo pudiera tolerar dos dosis por día?. ¿Esperaría usted que* $y$ *aumentará? ¿Los incrementos en su tolerancia más allá de tres dosis al día tendrían efecto en* $y$*?*

## Definición General 

Sea $f$ y $g_i$, $j = 1, . . . , J$ funciones mapeadas desde $\mathbb{R^n}$ a $\mathbb{R}$.

Considere el problema de maximización con restricciones de la siguiente manera:

$$
\max_{x = (x_1, . . . , x_n)} f(x) \hspace{0.3cm}sujeto\hspace{0.1cm} a\hspace{0.1cm} g_j(x)\geq 0, \hspace{0.2cm} j = 1, . . . . , J
$$

Esto nos quiere decir que existen $J$ restricciones, cada una de las cuales está representada por una función $g$.

Entonces, la la *función lagrangiana* se escribe de la siguiente manera:

$$
L(x,\lambda) = f(x) + \sum_{j=1}^J \lambda_j g_j(x)
$$

Llamamos $\lambda_j$, $j = 1, . . . , J$ Multiplicadores Lagrangianos.

Nuestro objetivo siempre, es encontrar un vector $(x^*, \lambda^*)$ que resuelva las ecuaciones

$$
\begin{eqnarray}
\frac{\partial L(x*,\lambda^*)}{\partial x_i} &=& 0,\hspace{0.3cm} \forall\hspace{0.1cm}  i= 1, . . . , n \\[0.2cm]
\lambda_j^*g_j^*(x^*) &=& 0,\hspace{0.1cm} y\hspace{0.2cm} \lambda_j*\geq 0\hspace{0.3cm}\forall \hspace{0.1cm} j = 1, . . . , J
\end{eqnarray}
$$

### Ejercicio a resolver en clase 

Plantee el problema de maximización de la utilidad de la siguiente manera:

$$
\max_{x = (x_1,x_2)} u(x)
$$

sujeto a

$$
\begin{eqnarray}
m - p_1x_1 - p_2x_2 &\geq& 0\\[0.2cm]
x_1 &\geq& 0\\[0.2cm]
x_2 &\geq& 0
\end{eqnarray}
$$

La función lagrangiana correspondiente a este problema se puede escribir como

$$
L(x_1,x_2,\lambda) = u(x_1,x_2) + \lambda_1x_1 + \lambda_2x_2 + \lambda_3(m - p_1x_1 - p_2x_2)
$$

A continuación asumiremos que

-   $u(x_1,x_2) = a\ln x_1 + (1-a)\ln x_2$,$\hspace{0.2cm}  a\in (0,1)$

-   $u(x_1,x_2) = x_1 + \ln x_2$ además supongamos que $(p_1, p_2, m) = (4,1,3)$

En cada caso correspondiente encuentre $x_1^*, x_2^*$.
